---
# tasks file for vaultwarden

- name: Download the API server RPM
  ansible.builtin.get_url:
    url: "{{ rpm_source }}/vaultwarden-{{ api_server_version }}.x86_64.rpm"
    dest: /tmp
    mode: 0644

- name: Download the web vault RPM
  ansible.builtin.get_url:
    url: "{{ rpm_source }}/vaultwarden-webvault-{{ web_vault_version }}.noarch.rpm"
    dest: /tmp
    mode: 0644

- name: Install the API server and web vault
  become: true
  ansible.builtin.package:
    name:
      - "/tmp/vaultwarden-{{ api_server_version }}.x86_64.rpm"
      - "/tmp/vaultwarden-webvault-{{ web_vault_version }}.noarch.rpm"
    disable_gpg_check: true
    state: present
  notify: Restart Vaultwarden service

- include_tasks: config.yml

- name: Uninstall Vaultwarden
  become: true
  ansible.builtin.package:
    name: vaultwarden
    state: absent
  tags:
    - never
    - uninstall

- name: Clean up RPM
  become: true
  ansible.builtin.file:
    path: "/tmp/vaultwarden-{{ api_server_version }}.x86_64.rpm"
    state: absent
  tags:
    - never
    - uninstall
